server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
         

#  redis:
#    host: redis
#    port: 6379
#logging:
#  level:
#    org.springframework: DEBUG
jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
logging:
  pattern:
    # Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"   
 
    
#whateger the custom proprs we will declare in ouryml ==> all declarations should happen towards the end.
 
    
